executable   = /user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/run_GEN-SIM.sh
arguments    = $(runnumber)
should_transfer_files = no
output       =/user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/output/gen-sim.out.$(runnumber)
error        = /user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/error/gen-sim.err.$(runnumber)
log          = /user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/log/gen-sim_condor.$(runnumber).log
universe     = vanilla
#+JobFlavour = "longlunch"
queue runnumber from params.txt 
