executable   = /user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/run_DIGI-RAW_alt.sh
arguments    = $(runnumber)
should_transfer_files = no
output       =/user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/output/digi-raw.out.$(runnumber)
error        = /user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/error/digi-raw.err.$(runnumber)
log          = /user/sdansana/HToSS-Search/CMSSW_12_0_2_patch1/src/NTupliser/generation/test/sample_scripts/log/digi-raw_condor.$(runnumber).log
universe     = vanilla
+JobFlavour = "workday"
queue runnumber from params_small.txt 
